apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubernetes-tutorial-replicaset
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubernetes-tutorial-replicaset
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-replicaset
    spec:
      containers:
        - name: kubernetes-tutorial-replicaset
          image: gautamborkar/kubernetes-tutorial
          ports:
            - containerPort: 8080
