apiVersion: v1
kind: ReplicationController
metadata:
  name: kubernetes-tutorial-rc
spec:
  replicas: 3
  selector:
    app: kubernetes-tutorial-rc
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-rc
    spec:
      containers:
        - name: kubernetes-tutorial-rc
          image: gautamborkar/kubernetes-tutorial
          ports:
            - containerPort: 8080
