apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: kubernetes-tutorial-certificatesigningrequest
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
    - digital signature
    - key encipherment
    - server auth
    