apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubernetes-tutorial-readinessprobe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-tutorial-replicaset
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-replicaset
    spec:
      containers:
        - name: kubernetes-tutorial-replicaset
          image: gautamborkar/kubernetes-tutorial
          readinessProbe:
            exec:
              command:
                - ls
                - /var/ready
          ports:
            - containerPort: 8080
