apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-tutorial-job
spec:
  completions: 5
  parallelism: 2
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      activeDeadlineSeconds: 1200
      containers:
        - name: main
          image: luksa/batch-job
